name: PracticeWorkFlow
on: [push, workflow_dispatch]
jobs:
    lintJob:
        runs-on: ubuntu_latest
        steps:
            - name: set up
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: lint
              run: npm run lint
            - name: install dependencies
              run: npm ci
            - name: test
              run: npm run test
            - name: build
              run: npm run build



