name: PracticeWorkFlow
on: push
jobs:
    lintJob:
        runs-on: ubuntu_latest
        steps:
            - name: set up
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: lint
              run: npm run lint
    testJob:
        runs-on: ubuntu_latest
        steps:
            - name: set up
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: test
              run: npm run test
    buildJob:
        runs-on: ubuntu_latest
        steps:
            - name: set up
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: build
              run: npm run build



